-- Drop tables in reverse order of creation
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS POLL_OPTIONS;
DROP TABLE IF EXISTS POLLS;
DROP TABLE IF EXISTS COURSE_MATERIALS;
DROP TABLE IF EXISTS APP_USERS;